#!/usr/bin/env python

# origin & instructions how to setup git-clang-format
# https://dx13.co.uk/articles/2015/4/3/Setting-up-git-clang-format.html

import subprocess
output = subprocess.check_output(["git", "clang-format", "--diff"])

if output not in ['no modified files to format\n',
                  'clang-format did not modify any files\n']:
    print "Run `git clang-format` then commit again, or "
    print "Use `git commit -n` to bypass pre-commit hook (not recommended).\n"
    exit(1)
else:
    exit(0)
